// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"
)

type Attachment struct {
	ID           int64
	Uuid         string
	Type         string
	FileName     string
	FileType     string
	FileSize     int64
	Persondataid int64
	Createdat    sql.NullTime
}

type Person struct {
	ID             int64
	Uuid           string
	Name           string
	Sex            string
	DateOfBirth    time.Time
	PlaceOfBirth   string
	FatherName     string
	Contact        string
	OccupationType string
	Budget         float64
	AnnualIncome   float64
	Notes          string
	Createdat      sql.NullTime
	Modifiedat     sql.NullTime
}
