// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {time} from '../models';

export function GetAllOccupationTypes():Promise<Array<string>>;

export function GetAttachmentBase64(arg1:string):Promise<string>;

export function GetAttachmentsByUUID(arg1:string):Promise<Array<data.Attachment>>;

export function GetPersonByID(arg1:number):Promise<data.Person>;

export function InsertAttachments(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InsertPerson(arg1:string,arg2:string,arg3:time.Time,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:string,arg10:string,arg11:string,arg12:string):Promise<void>;

export function ListPersonsByName():Promise<Array<data.Person>>;

export function OpenMultipleFileSelectDialog():Promise<Array<string>>;

export function UpdateNoteForPerson(arg1:string,arg2:number):Promise<void>;

export function UpdatePerson(arg1:number,arg2:string,arg3:string,arg4:time.Time,arg5:string,arg6:string,arg7:string,arg8:number,arg9:number,arg10:string,arg11:string):Promise<void>;
