// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllOccupationTypes() {
  return window['go']['main']['App']['GetAllOccupationTypes']();
}

export function GetAttachmentBase64(arg1) {
  return window['go']['main']['App']['GetAttachmentBase64'](arg1);
}

export function GetAttachmentsByUUID(arg1) {
  return window['go']['main']['App']['GetAttachmentsByUUID'](arg1);
}

export function GetPersonByID(arg1) {
  return window['go']['main']['App']['GetPersonByID'](arg1);
}

export function InsertAttachments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertAttachments'](arg1, arg2, arg3, arg4);
}

export function InsertPerson(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['InsertPerson'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function ListPersonsByName() {
  return window['go']['main']['App']['ListPersonsByName']();
}

export function OpenMultipleFileSelectDialog() {
  return window['go']['main']['App']['OpenMultipleFileSelectDialog']();
}

export function UpdateNoteForPerson(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteForPerson'](arg1, arg2);
}

export function UpdatePerson(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdatePerson'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
